debug: ${debug} # inherited from configurations/config.yaml
lr: ${experiment.training.lr}

# dataset-dependent configurations
x_shape: ${model.observation_shape}
external_cond_dim: 8
chunk_size: 1 # -1 for full trajectory diffusion, number to specify diffusion chunk size

n_frames: 20

# training hyperparameters
weight_decay: 2e-3
warmup_steps: 10000
optimizer_beta: [0.9, 0.99]
strategy: ${experiment.training.strategy}

rag_weight: [10, 10, 10, 3]
similarity_func: euclidean
retrieve_num: 10
retrieve_noise_level: 200

retrieve_strategy: single
loss_strategy: single

diffusion:
# training
  schedule_fn_kwargs: {}
  snr_clip: 5.0
  timesteps: 1000
  cum_snr_decay: 0.96
  clip_noise: 6.
  # sampling
  sampling_timesteps: 40 # fixme, numer of diffusion steps, should be increased
  stabilization_level: 15
  predict_v: true

metrics:
  - nothing
  # - fvd
  # - fid
  # - lpips