# configuration parsing starts here
defaults:
  - experiment: exp # experiment yaml file name in configurations/experiments folder [fixme]
  - dataset: minecraft_easy # dataset yaml file name in configurations/dataset folder [fixme]
  - algorithm: df_gan # algorithm yaml file name in configurations/algorithm folder [fixme]
  - model: dit # model yaml file name in configurations/model folder [fixme]
  - cluster: null # optional, cluster yaml file name in configurations/cluster folder. Leave null for local compute

debug: false # global debug flag will be passed into configuration of experiment, dataset and algorithm

wandb:
  entity: tychen0028 # wandb account name / organization name [fixme]
  project: diffusion-forcing # wandb project name; if not provided, defaults to root folder name [fixme]
  mode: offline # set wandb logging to online, offline or dryrun

resume: null # wandb run id to resume logging and loading checkpoint from
load: null # wandb run id containing checkpoint or a path to a checkpoint file

name: apt

experiment:
  model_ckpt: outputs/2025-03-25/16-03-09/checkpoints/epoch=2-step=20000.ckpt # path to a pre-trained diffusion checkpoint
  tasks: [training]
  training:
    precision: bf16-mixed
    devices: auto
    strategy: ddp
    batch_size: 12
    max_epochs: 3
    checkpointing:
      every_n_train_steps: 2000
    optim:
      gradient_clip_val: 0
  validation:
    precision: bf16-mixed
    strategy: ddp
    batch_size: 8
    limit_batch: 1
    val_every_n_step: null
    val_every_n_epoch: 50
  
algorithm:
  save_video_every_n_step: 2000
  warmup_steps: 2000
  mse_loss_coeff: 1.0
  gen_gan_loss_coeff: 5.0
  noise_real_image: false

model:
  precision: bf16-mixed
