# configuration parsing starts here
defaults:
  - experiment: exp # experiment yaml file name in configurations/experiments folder [fixme]
  - dataset: minerl # dataset yaml file name in configurations/dataset folder [fixme]
  - algorithm: attn_mem_video # algorithm yaml file name in configurations/algorithm folder [fixme]
  - model: attn_mem_dit # model yaml file name in configurations/model folder [fixme]
  - cluster: null # optional, cluster yaml file name in configurations/cluster folder. Leave null for local compute

debug: false # global debug flag will be passed into configuration of experiment, dataset and algorithm

wandb:
  entity: tychen0028 # wandb account name / organization name [fixme]
  project: diffusion-forcing # wandb project name; if not provided, defaults to root folder name [fixme]
  mode: offline # set wandb logging to online, offline or dryrun

resume: null # wandb run id to resume logging and loading checkpoint from
load: null # wandb run id containing checkpoint or a path to a checkpoint file

name: attn_mem

experiment:
  model_ckpt: null
  tasks: [training]
  training:
    precision: bf16-mixed
    devices: auto
    strategy: ddp
    batch_size: 2
    checkpointing:
      every_n_train_steps: 10000
  validation:
    precision: bf16-mixed
    strategy: ddp
    batch_size: 2
    limit_batch: 1
    val_every_n_step: 3000

dataset:
  n_frames: 32
  context_length: 4
  validation_multiplier: 2