# configuration parsing starts here
hydra:
  run:
    dir: your_output_path

defaults:
  - experiment: exp # experiment yaml file name in configurations/experiments folder [fixme]
  - dataset: scannet # dataset yaml file name in configurations/dataset folder [fixme]
  - algorithm: df_video # algorithm yaml file name in configurations/algorithm folder [fixme]
  - model: scannet_dit # model yaml file name in configurations/model folder [fixme]
  - cluster: null # optional, cluster yaml file name in configurations/cluster folder. Leave null for local compute

debug: false # global debug flag will be passed into configuration of experiment, dataset and algorithm

wandb:
  entity: tychen0028 # wandb account name / organization name [fixme]
  project: diffusion-forcing # wandb project name; if not provided, defaults to root folder name [fixme]
  mode: offline # set wandb logging to online, offline or dryrun

resume: null # wandb run id to resume logging and loading checkpoint from
load: null # wandb run id containing checkpoint or a path to a checkpoint file

name: scannet_df8

experiment:
  seed: 42
  model_ckpt: null
  tasks: [training]
  training:
    precision: bf16-mixed
    devices: auto
    strategy: deepspeed
    batch_size: 64
    max_epochs: 1
    checkpointing:
      every_n_train_steps: 400
  validation:
    precision: bf16-mixed
    strategy: deepspeed
    batch_size: 8
    limit_batch: 1
    val_every_n_step: null
    val_every_n_epoch: 50

algorithm:
  warmup_steps: 400
  vae_name: sd_vae
  vae_ckpt: stabilityai/sd-vae-ft-mse