# configuration parsing starts here
defaults:
  - experiment: exp # experiment yaml file name in configurations/experiments folder [fixme]
  - dataset: minerl # dataset yaml file name in configurations/dataset folder [fixme]
  - algorithm: df_video # algorithm yaml file name in configurations/algorithm folder [fixme]
  - model: dit # model yaml file name in configurations/model folder [fixme]
  - cluster: null # optional, cluster yaml file name in configurations/cluster folder. Leave null for local compute

debug: false # global debug flag will be passed into configuration of experiment, dataset and algorithm

wandb:
  entity: tychen0028 # wandb account name / organization name [fixme]
  project: diffusion-forcing # wandb project name; if not provided, defaults to root folder name [fixme]
  mode: offline # set wandb logging to online, offline or dryrun

resume: null # wandb run id to resume logging and loading checkpoint from
load: null # wandb run id containing checkpoint or a path to a checkpoint file

name: latent_diffusion

experiment:
  tasks: [training]
  training:
    precision: 16-mixed
    devices: [4,5,6,7]
    strategy: ddp
    batch_size: 8
  validation:
    batch_size: 8
    limit_batch: 1
    val_every_n_step: 2000
  checkpointing:
    every_n_train_steps: 3000
  
algorithm:
  warmup_steps: 5000
  vae_ckpt: /data/taiye/Project/open-oasis/models/oasis500m/vit-l-20.safetensors