# configuration parsing starts here
hydra:
  run:
    dir: outputs/rnn/ttt_comb_onemem_b256

defaults:
  - experiment: exp # experiment yaml file name in configurations/experiments folder [fixme]
  - dataset: maze # dataset yaml file name in configurations/dataset folder [fixme]
  - algorithm: df_rnn_video # algorithm yaml file name in configurations/algorithm folder [fixme]
  - model: rnn_ttt_maze # model yaml file name in configurations/model folder [fixme]
  - cluster: null # optional, cluster yaml file name in configurations/cluster folder. Leave null for local compute

debug: false # global debug flag will be passed into configuration of experiment, dataset and algorithm

wandb:
  entity: tychen0028 # wandb account name / organization name [fixme]
  project: diffusion-forcing # wandb project name; if not provided, defaults to root folder name [fixme]
  mode: offline # set wandb logging to online, offline or dryrun

resume: null # wandb run id to resume logging and loading checkpoint from
load: null # wandb run id containing checkpoint or a path to a checkpoint file

name: ttt_comb_onemem_b256

experiment:
  model_ckpt: null # path to a pre-trained diffusion checkpoint
  tasks: [training]
  training:
    precision: bf16-mixed
    devices: auto
    strategy: deepspeed
    batch_size: 8
    max_epochs: 5
    log_every_n_steps: 1
    checkpointing:
      every_n_train_steps: 407
      enable_version_counter: True
      filename: ckpt-{epoch}-{step}
      save_top_k: 10
      monitor: epoch
  validation:
    precision: bf16-mixed
    strategy: deepspeed
    batch_size: 8
    limit_batch: 2
    val_every_n_step: 407
    val_every_n_epoch: null
  
algorithm:
  warmup_steps: 20
  training_chunk_num: 256
  lstm_mini_batch_size: 128
  training_mini_batch_size: 8
  auxiliary_loss_coeff: 0.0

dataset:
  pre_load: false
  n_frames: 1001
  external_cond_dim: 10
  action_types: [action, agent_pos, agent_dir]