debug: ${debug} # inherited from configurations/config.yaml

n_frames: 100 # TODO: increase later
action_type: action # action, pos, both
pre_load: false
metadata:
  - /home/tc0786/Project/train-oasis/data/mem_encoded_data/20k.json
  - /home/tc0786/Project/train-oasis/data/mem_encoded_data/metadata_mem.json
limit_video_length:
  - null
  - null